### ISSUE TITLE
Banner: When banner contents move down, align button label at the center vertically and horizontally.

### ISSUE THREAD

**Issue by ricatitan** [titan-cebu/Rokeby-Dental#100]
![image](https://cloud.githubusercontent.com/assets/18568310/17315883/febc7074-58a1-11e6-94f4-71a9e42a12b6.png)

**Comment by ricatitan** [comment]
Clipped text and button labels are not aligned in the center i 1199px resolution. Please see screenshot.

![image](https://cloud.githubusercontent.com/assets/18568310/17577389/a5aabbfc-5faf-11e6-945d-66b79f279a26.png)

**Comment by titandigitalbkk** [comment]
fixed
