### ISSUE TITLE
Homepage - Meet our team: Incomplete posts when during responsive testing and it does not navigate

### ISSUE THREAD

**Issue by ricatitan** [titan-cebu/Rokeby-Dental#101]
![image](https://cloud.githubusercontent.com/assets/18568310/17315941/906306a0-58a2-11e6-9099-41eab68e1427.png)

**Comment by ricatitan** [comment]
Error can be reproduce still.

steps to reproduce:
1. You resize your website going in the lower resolution
2. Resize the website goint in the higher resolution
Notice: Incomplete posts will show and it wont navigate. See screenshot below. 


![image](https://cloud.githubusercontent.com/assets/18568310/17576662/af53e03c-5fa7-11e6-816a-200b32fb472a.png)

**Comment by titandigitalbkk** [comment]
fixed
