### ISSUE TITLE
Homepage- Meet Our team: Responsive error from 992px above

### ISSUE THREAD

**Issue by ricatitan** [titan-cebu/Rokeby-Dental#102]
![image](https://cloud.githubusercontent.com/assets/18568310/17315976/ce2854c2-58a2-11e6-90ec-7fd565240134.png)

**Comment by ricatitan** [comment]
Image is pixelated and cut in 767px and below resolution

![image](https://cloud.githubusercontent.com/assets/18568310/17576642/76ada6dc-5fa7-11e6-9dca-704aa0a1ca1d.png)

**Comment by titandigitalbkk** [comment]
fixed

**Comment by ricatitan** [comment]
Image is still stretched
![image](https://cloud.githubusercontent.com/assets/18568310/17847546/1e158e44-6881-11e6-905d-66e2479b04c1.png)
