### ISSUE TITLE
Our Practitioners: Make the pagination arrow smaller as per design 

### ISSUE THREAD

**Issue by ricatitan** [titan-cebu/Rokeby-Dental#110]
![image](https://cloud.githubusercontent.com/assets/18568310/17316491/f445ec42-58a6-11e6-8be1-c2135035120c.png)

**Comment by p-wanlaphakorn** [comment]
I think it shouldn't show the previous page. it's on first page now.

**Comment by ricatitan** [comment]
What im refering to is the arrow inside the pagination. Please make it longer as per design
![image](https://cloud.githubusercontent.com/assets/18568310/17576424/4e28a808-5fa5-11e6-9f31-236ecdaab536.png)

**Comment by titandigitalbkk** [comment]
fixed.
i have make them a bit smaller and bolder.
