### ISSUE TITLE
Contact Us: Incorrect font size 

### ISSUE THREAD

**Issue by ricatitan** [titan-cebu/Rokeby-Dental#112]
![image](https://cloud.githubusercontent.com/assets/18568310/17316728/fdb0333a-58a8-11e6-9703-87785773d3b0.png)

**Comment by ricatitan** [comment]
Observe exact spacing between fields and margin height for fields
![image](https://cloud.githubusercontent.com/assets/18568310/17576340/3060b6f4-5fa4-11e6-841a-199686cf96a6.png)

**Comment by titandigitalbkk** [comment]
fixed

**Comment by ricatitan** [comment]
All font style must be arial and has 15px. Please see in the design.

Can you please align also the form to the business details?

![image](https://cloud.githubusercontent.com/assets/18568310/17846809/2d426792-687d-11e6-9cd2-838b26e1a3bd.png)
