### ISSUE TITLE
Homepage sections: If blog/meet our team is empty, or the section is empty, remove the section title

### ISSUE THREAD

**Issue by ricatitan** [titan-cebu/Rokeby-Dental#120]
![image](https://cloud.githubusercontent.com/assets/18568310/17579513/1a02cb02-5fc9-11e6-8aee-cb6f935d13e5.png)

![image](https://cloud.githubusercontent.com/assets/18568310/17579547/58aa6176-5fc9-11e6-96b3-8ea080a2c045.png)

**Comment by titandigitalbkk** [comment]
fixed
