### ISSUE TITLE
Footer: Footer menu text overlaps

### ISSUE THREAD

**Issue by ricatitan** [titan-cebu/Rokeby-Dental#121]
![image](https://cloud.githubusercontent.com/assets/18568310/17579582/abaef454-5fc9-11e6-82b7-b796371cb797.png)

**Comment by titandigitalbkk** [comment]
fixed

**Comment by ricatitan** [comment]
Incorrect font size and font style

![image](https://cloud.githubusercontent.com/assets/18568310/17842171/9c1fb212-6852-11e6-82bf-59f2376fa39e.png)
