### ISSUE TITLE
Leadins: If image is not set, add default no image so that it will go up and it will still be align.

### ISSUE THREAD

**Issue by ricatitan** [titan-cebu/Rokeby-Dental#122]
![image](https://cloud.githubusercontent.com/assets/18568310/17579638/377a268e-5fca-11e6-8bae-dcdc7b87823a.png)

**Comment by titandigitalbkk** [comment]
fixed

**Comment by ricatitan** [comment]
If title is empty, title section is cut.
![image](https://cloud.githubusercontent.com/assets/18568310/17841976/a645447a-6850-11e6-9e1c-72e74b961641.png)
