### ISSUE TITLE
Services: Only in chrome and opera browser has shorten text, no shorten text in i.e, edge and mozilla browser

### ISSUE THREAD

**Issue by ricatitan** [titan-cebu/Rokeby-Dental#128]
![image](https://cloud.githubusercontent.com/assets/18568310/17580114/76d2fb9a-5fce-11e6-8b6e-6c29a08899e2.png)

**Comment by titandigitalbkk** [comment]
both browser already shorten text (5 lines) but only chrome and opera will showing [...] as this stylesheet only except in this 2 browser.

**Comment by ricatitan** [comment]
**It must show in all browser.** 
In homepage-featured blog, where there is also shorten text, it shows in all browser 

![image](https://cloud.githubusercontent.com/assets/18568310/17845631/de89cb42-6875-11e6-9565-9829a748ab6e.png)
![image](https://cloud.githubusercontent.com/assets/18568310/17845660/18318d76-6876-11e6-9a4e-b44ea683780b.png)
