### ISSUE TITLE
Services Page/Services Listing: Featured image is not shown in the design

### ISSUE THREAD

**Issue by ricatitan** [titan-cebu/Rokeby-Dental#129]
![image](https://cloud.githubusercontent.com/assets/18568310/17580163/1a26be58-5fcf-11e6-9460-0934031b1121.png)

![image](https://cloud.githubusercontent.com/assets/18568310/17580389/d8b702b4-5fd0-11e6-9e18-1c5b05896cac.png)

**Comment by titandigitalbkk** [comment]
fixed
