### ISSUE TITLE
Banner: button label is cut and it is not align in the center in 1199px resolution

### ISSUE THREAD

**Issue by ricatitan** [titan-cebu/Rokeby-Dental#131]
![image](https://cloud.githubusercontent.com/assets/18568310/17577433/3f0fd6b0-5fb0-11e6-9d0a-a0c0f59b4cb0.png)

**Comment by titandigitalbkk** [comment]
fixed

**Comment by ricatitan** [comment]
No space in between banner image and contents
![image](https://cloud.githubusercontent.com/assets/18568310/17845511/01aad022-6875-11e6-8e88-63778e8334b5.png)

**Comment by ricatitan** [comment]
Icon and "schedule an appointment" is too far compare in the design
![image](https://cloud.githubusercontent.com/assets/18568310/18077890/0c6cc492-6ebb-11e6-9e16-42ade5d3dc20.png)
