### ISSUE TITLE
Sidebar: should not select date later than the current date in preferred date field

### ISSUE THREAD

**Issue by dremensayson** [titan-cebu/Rokeby-Dental#18]
![image](https://cloud.githubusercontent.com/assets/17717843/16722400/ea3bdd22-4778-11e6-9b22-99fa7d51444e.png)

**Comment by p-wanlaphakorn** [comment]
This field is changed to dropdown field for choosing the date (monday, tuesday, etc.) as confirmed with TL.

**Comment by ricatitan** [comment]
Is there any change request document for this?

**Comment by p-wanlaphakorn** [comment]
![image](https://cloud.githubusercontent.com/assets/18691989/17538874/bd341aca-5ed3-11e6-9fc8-ce7d713efc41.png)
