### ISSUE TITLE
Homepage - Featured Blog: Align the contents regardless if the post title has one line or two lines so that the buttons will be align

### ISSUE THREAD

**Issue by ricatitan** [titan-cebu/Rokeby-Dental#43]
![image](https://cloud.githubusercontent.com/assets/18568310/16753195/5efc4cd6-481a-11e6-93bf-aa25df1e9914.png)

**Comment by ricatitan** [comment]
It is already fixed and then I'll reopen again coz it the error occurs again.
![image](https://cloud.githubusercontent.com/assets/18568310/17579487/d4ce8e54-5fc8-11e6-839e-48f3811b1a2a.png)

**Comment by titandigitalbkk** [comment]
fixed
