### ISSUE TITLE
Services: small space between images compared to the design

### ISSUE THREAD

**Issue by dremensayson** [titan-cebu/Rokeby-Dental#48]
![image](https://cloud.githubusercontent.com/assets/17717843/16754039/598c8674-4821-11e6-946a-1d76aea25f12.png)

**Comment by p-wanlaphakorn** [comment]
I think the column of design is not the same as the column of  bootstrap standard. 
The design the column is 12 - 4 [see the image below]
![image](https://cloud.githubusercontent.com/assets/18691989/17126155/aa2d2c6a-5324-11e6-88b7-a54ce667616c.png)

the bootstrap standard is 8-4 [see the image below]

![image](https://cloud.githubusercontent.com/assets/18691989/17126192/051feb1c-5325-11e6-8ca4-93ca1bf63c0d.png)
