### ISSUE TITLE
Leadins: Leadins and video doensn't have same margin height during responsive testing in 1199px resolution

### ISSUE THREAD

**Issue by ricatitan** [titan-cebu/Rokeby-Dental#59]
![image](https://cloud.githubusercontent.com/assets/18568310/16754662/4182a904-4827-11e6-9eab-64e99bba6f13.png)

**Comment by ricatitan** [comment]
![image](https://cloud.githubusercontent.com/assets/18568310/17314822/ad72277a-5899-11e6-9aac-a091b3c66bf4.png)

**Comment by ricatitan** [comment]
Still not align 
![image](https://cloud.githubusercontent.com/assets/18568310/17577898/892d1546-5fb5-11e6-8adb-99e4c402dd65.png)

**Comment by titandigitalbkk** [comment]
fixed
