### ISSUE TITLE
Breadcrumbs: font awesome is not implemented as per design

### ISSUE THREAD

**Issue by dremensayson** [titan-cebu/Rokeby-Dental#6]
![image](https://cloud.githubusercontent.com/assets/17717843/16721213/19fb780a-4770-11e6-8402-e817b2f180e6.png)

**Comment by p-wanlaphakorn** [comment]
I have one question for this issue.
Does it need to implement as per design if it has other solution? 
For font awesome icon, there is other solution to work on it. 
for example, %gt; entity html. I think it's the same symbol. '>'
I look forward to hearing from you.
thanks. :)
