### ISSUE TITLE
Homepage Content: Clipped text during responsive testing.

### ISSUE THREAD

**Issue by ricatitan** [titan-cebu/Rokeby-Dental#61]
![image](https://cloud.githubusercontent.com/assets/18568310/16755659/9727669c-4831-11e6-830e-ed962504c759.png)

**Comment by ricatitan** [comment]
465px

![image](https://cloud.githubusercontent.com/assets/18568310/17579870/16ce0548-5fcc-11e6-9038-ef77fb7fb03a.png)

**Comment by titandigitalbkk** [comment]
fixed
