### ISSUE TITLE
Blog: title is  limited to one line as per scope

### ISSUE THREAD

**Issue by dremensayson** [titan-cebu/Rokeby-Dental#68]
![image](https://cloud.githubusercontent.com/assets/17717843/16756136/a88a0378-4835-11e6-9fdb-d89c7844b97e.png)

**Comment by ricatitan** [comment]
Remove shorten text in the title

![image](https://cloud.githubusercontent.com/assets/18568310/17289041/725cc27e-580a-11e6-8712-335433bca296.png)
