### ISSUE TITLE
Blog: pagination is not implemented

### ISSUE THREAD

**Issue by dremensayson** [titan-cebu/Rokeby-Dental#70]
![image](https://cloud.githubusercontent.com/assets/17717843/16756255/91505224-4836-11e6-8b55-1579c0256320.png)

**Comment by ricatitan** [comment]
Should paginate after 5 posts not in 6 post

![image](https://cloud.githubusercontent.com/assets/18568310/17288996/3ef1a814-580a-11e6-81ec-374f7f5e7cb3.png)
