### ISSUE TITLE
Inner Pages: space between content and footer are to small compared to the design

### ISSUE THREAD

**Issue by dremensayson** [titan-cebu/Rokeby-Dental#9]
![image](https://cloud.githubusercontent.com/assets/17717843/16721614/41e6e6da-4773-11e6-8dca-6cb6271f4134.png)

**Comment by ricatitan** [comment]
![image](https://cloud.githubusercontent.com/assets/18568310/17314438/01025d68-5897-11e6-9469-0d8c83a1d05a.png)

**Comment by ricatitan** [comment]
Incorrect landing page, it should be titan digital
![image](https://cloud.githubusercontent.com/assets/18568310/18079502/b372218a-6ec3-11e6-9e50-f6ed46dbc2a7.png)
