### ISSUE TITLE
Banner: Navigation button is way smaller compare  in the design

### ISSUE THREAD

**Issue by ricatitan** [titan-cebu/Rokeby-Dental#92]
![image](https://cloud.githubusercontent.com/assets/18568310/17315249/c8cc6528-589c-11e6-8fc7-e5d68bbbe54f.png)

**Comment by ricatitan** [comment]
Add enough space in between navigation buttons as per design.

![image](https://cloud.githubusercontent.com/assets/18568310/17577479/c5c265ec-5fb0-11e6-92a2-511bdca064b6.png)

**Comment by titandigitalbkk** [comment]
fixed
